import pandas as pd
import re
from pathlib import Path

#No longer useful
def clean_name(name):
    """Cleans names by removing tickers (NYS: BX) and people in parentheses."""
    if not isinstance(name, str): return name
    # Remove text in parentheses: e.g., (NYS: BX) or (John Smith)
    name = re.sub(r'\([^)]*\)', '', name)
    # Remove extra spaces
    return name.strip()


def generate_manual_mapping_template(raw_list):
    # 1. Clean and split the comma-separated strings
    # Many rows have multiple buyers (e.g., "Ares, Berkshire Partners")
    all_entities = []
    for entry in raw_list:
        if isinstance(entry, str):
            # Split by comma but ignore commas inside parentheses if any remain
            parts = [p.strip() for p in entry.split(',')]
            all_entities.extend([clean_name(p) for p in parts])

    # 2. Get unique list and sort alphabetically
    unique_entities = sorted(list(set([e for e in all_entities if e])))

    # 3. Create DataFrame for manual entry
    df = pd.DataFrame(unique_entities, columns=['Raw_Buyer_Name'])

    # Add the columns needed for your Professor's 3 Dimensions
    df['Parent_Entity'] = ""  # Step 2: Standardize (e.g. KKR)
    df['Entity_Type'] = ""  # Step 3: (Corporate, PE Firm, Public Market, Management)
    df['Is_Original_Sponsor'] = ""  # Step 4: (Boolean Y/N - to be compared against your master)
    df['Manual_Dimension'] = ""  # Final Tag: (1. Arm's Length, 2. PE Club, 3. Original Sponsor)

    # 4. Save to Excel for manual work
    output_path = Path("acquirer_mapping_v1.xlsx")
    df.to_excel(output_path, index=False)
    print(f"Success! Template created with {len(df)} unique entities.")
    print(f"File saved to: {output_path.absolute()}")


# The list you provided
acquirer_data = [
    "Allied Capital, Stone Arch Capital",
    "TAT Technologies (TAE: TATT)",
    "A.B.C. Learning Centres",
    "JD Sports Fashion (LON: JD.)(Regis Schultz)",
    "CVC Capital Partners (AMS: CVC)(Fred Watt), Flint Group",
    "Graphic Packaging (Acquired in 1988)",
    "LumaSense Technologies(Vivek Joshi)",
    "RFE Investment Partners(Michael Foster)",
    "Levitz Furniture",
    "Dave & Buster's (NAS: PLAY)",
    "NPC International(James Schwartz), Olympus Partners",
    "Wilshire Finance Partners",
    "Texas Molecular",
    "Harbour Point Capital(Robert Juneja), Irving Place Capital(Robert Juneja)",
    "Sun Healthcare Group(Richard Matros)",
    "Earl Enterprises(Robert Earl)",
    "TrueBlue (NYS: TBI)(Steven Cooper)",
    "Blue Point Capital Partners(John Kirby), Reynolda Equity Partners(Martin Gilmore)",
    "Linsalata Capital Partners(Gregory Taber), PNC Erieview Capital, Resilience Capital Partners(Bassem Mansour)",
    "Ares Management (NYS: ARES), Berkshire Partners(D. Peeler)",
    "Carson Private Capital, Lion Capital",
    "Prospect Hill Growth Partners",
    "Delta Galil Industries (TAE: DELG)",
    "Interstate Hotels and Resorts",
    "Cerberus Capital Management, TransCentra",
    "Brynwood Partners",
    "OFS Brands Holdings(Hank Menke)",
    "DJO Global",
    "22C Capital, CapVest Partners(Jamie Mintern), ICG Enterprise Trust",
    "Propex Operating Company",
    "AEA Investors(Brian Hoesterey), Starr Investment Holdings",
    "Deutsche Bank (ETR: DBK), TowerBrook Capital Partners, Wilton Brands(Steven Fraser)",
    "Canadian Imperial Bank of Commerce (TSE: CM)",
    "TXNM Energy (NYS: TXNM)(Patricia Collawn)",
    "Irving Place Capital(Douglas Korn)",
    "Jarden (Industrial Supplies and Parts)(James Lillie)",
    "AMETEK (NYS: AME)(David Zapico)",
    "Crestview Partners(Richard Demartini), Green Bankshares",
    "Abu Dhabi Investment Authority(Colm Lanigan), Freeman Spogli(J. Frederick Simmons), Goldman Sachs Asset Management, HarbourVest Partners(Peter Lipson), JZ Capital Partners (LON: JZCP), Leonard Green & Partners(John Danhakl), Stockwell Capital, TPG (NAS: TPG)(Jonathan Coslet)",
    "FTI Consulting (NYS: FCN)",
    "Quad-C Management",
    "Ball (NYS: BALL)",
    "Dimensional Associates, JDS Capital Management(Daniel Stein)",
    "Watsco (NYS: WSO)",
    "aPriori Capital Partners, Roark Capital Group(Neal Aronson)",
    "Fifth Third Bancorp (NAS: FITB)",
    "Willis Stein & Partners",
    "J.H. Whitney Capital Partners(Paul Vigano)",
    "Hellman & Friedman(Erik Ragatz)",
    "Forest Oil",
    "AE Industrial Partners(David Rowe)",
    "Spherion Staffing(Roy Krause)",
    "Red Zone Capital Management, Six Flags",
    "Wayzata Investment Partners",
    "Multek(Werner Widmann)",
    "Audax Private Equity, Wind Point Partners(Nathan Brown)",
    "Freestone Partners(Mark Leyerle), Patriot Capital(Patrick Hamner)",
    "Beacon Bay Holdings, FGX International, PNC Erieview Capital",
    "Thomas H. Lee Partners",
    "Activant Solutions(Larry Jones), HM Capital (Thrifts and Mortgage Finance)(Andrew Rosen)",
    "ATP Private Equity Partners, BC Partners(Raymond Svider), CPP Investments",
    "Castle Harlan(Justin Wender), MCG Capital, The AMES Companies(Richard Dell)",
    "Microsoft Advertising(Brian Mcandrews)",
    "Varsity Brands",
    "The Stephens Group(Kent Sorrells)",
    "Privileged Access",
    "Bear Growth Capital Partners",
    "SGK",
    "CDC Software (Atlanta), Rotunda Capital Partners, Vista Equity Partners(Marc Teillon)",
    "Madison Dearborn Partners",
    "BT Group (LON: BT.A)",
    "Noble Energy (Gulf of Mexico Shelf Assets)",
    "The Carlyle Group (NAS: CG)",
    "Battery Ventures, General Atlantic(Anton Levy), Pivotal Group, Sonostar Capital Partners, Sonostar Ventures",
    "New Mountain Capital(Matthew Lori), Silver Canyon Group",
    "United Online",
    "Castle Harlan",
    "Marsh & McLennan Companies (NYS: MMC)",
    "Tata Chemicals (BOM: 500770)",
    "Taylor Communications",
    "ExlService Holdings (NAS: EXLS)(Rohit Kapoor)",
    "Littlejohn & Co.(Brian Ramsay), Strategic Value Partners",
    "Brookfield Oaktree Holdings",
    "Istithmar World",
    "Level 3 Communications",
    "Formula Telecom Solutions(Amos Sivan)",
    "Third Avenue Management",
    "Dalian Wanda Group(Jianlin Wang)",
    "Coty (NYS: COTY)",
    "Esko(Carsten Knudsen)",
    "Starwood Capital Group, Starwood Property Trust (NYS: STWD)(Barry Sternlicht)",
    "Blue Yonder (Scottsdale)(Mike Mayoras)",
    "Service Corporation International (NYS: SCI)(Thomas Ryan)",
    "Broadvox",
    "Centre Lane Partners(Quinn Morgan)",
    "Bryant Stibel, Kohlberg Kravis Roberts (NYS: KKR)(Nathaniel Taylor)",
    "Alumni Ventures, Sailing Capital, Sanpower Group",
    "Ares Management (NYS: ARES)(Dennis Gies), CPP Investments(Andre Bourbonnais)",
    "Newfold Digital(David Brown)",
    "PTC (NAS: PTC)(James Heppelmann)",
    "Brookfield Property Partners",
    "Advent International(Jeff Case), Cohesive Capital Partners, Thomas H. Lee Partners(Todd Abbrecht)",
    "Eagle Private Capital, Gen Cap America",
    "Blue Sage Capital, Stellus Capital Management (NYS: SCM)",
    "TFI International (TSE: TFII)(Alain Bedard)",
    "HGGC(Richard Lawson), Stockwell Capital",
    "UnitedHealth Group (NYS: UNH)(David Wichmann)",
    "Crown Predator Holdings, EG Capital Group(Jay Eastman)",
    "Fluidra (MAD: FDR)(Eloi Corts)",
    "Ardagh Group(Paul Coulson)",
    "Dick's Sporting Goods (NYS: DKS)",
    "Proveho Capital(William Koneval), Regent(Michael Reinstein)",
    "Hunt Consolidated, Sharyland Utilities",
    "Novolex Holdings(Stanley Bikulege), Wind Point Partners(Alex Washington)",
    "Heartwood Partners(Russell Spieler), M&Q Packaging(Michael Schmal)",
    "Vantage Hospitality Group",
    "Warburg Pincus(James Neary)",
    "ACCESS Newswire (ASE: ACCS)(Brian Balbirnie)",
    "Matcor-Matsu Group",
    "Gemspring Capital(Thomas Zanios)",
    "Universal Technical Institute (NYS: UTI)(Jerome Grant)",
    "Specialty Steel Works",
    "CPP Investments(Shane Feeney), CVC Capital Partners (AMS: CVC)(Christopher Stadler)",
    "Hexagon (STO: HEXA B)(Ola RollÃ©n)",
    "Sterling Investment Partners(Charles Santoro)",
    "Arvato Digital Services",
    "Texas Hydraulics(Patrick Taylor), Wynnchurch Capital(Frank Hayes)",
    "Novelis(Steven Fisher)",
    "Pentair (NYS: PNR)(Randall Hogan)",
    "HEICO (NYS: HEI.A)(Laurans Mendelson)",
    "Leonard Green & Partners(Usama Cortas), Snyder Industries",
    "AmTrust Financial Services(Barry Zyskind)",
    "Investindustrial(Andrea Bonomi), Nottingham Spirk(Bill Nottingham)",
    "Goldman Sachs Asset Management, Olympus Partners(Manu Bettegowda)",
    "Centerbridge Partners(Bao Truong)",
    "Balmoral Funds(Jonathan Victor)",
    "ForgeLight(Wade Davis), Searchlight Capital Partners(Eric Zinterhofer), Tikehau Capital (PAR: TKO)",
    "National General(Barry Karfunkel)",
    "Universal Molding",
    "EQT (STO: EQT)(Glen Matsumoto)",
    "Gemalto(Olivier Piou)",
    "Integrated Medical Technologies(Frank Tomori)",
    "Barclays (LON: BARC), Baylor Scott & White Health, NatWest Group (LON: NWG)",
    "Carvana (NYS: CVNA)(Ernest Garcia)",
    "Blackstone (NYS: BX)",
    "Onex (Private Equity) (TSE: ONEX)",
    "Waterfall Asset Management",
    "SP Plus(James Wilhelm)",
    "AlpInvest Partners, GIC Private(Alex Moskowitz), HarbourVest Partners(Ian Lane), Hellman & Friedman(David Tunnell)",
    "Deutsche Bank (ETR: DBK), RBS Global",
    "Dean Foods(Gregg Tanner)",
    "Barnes & Noble",
    "Welltower (NYS: WELL)(George Chapman)",
    "Prospect Capital Management",
    "Grupo Mexico (MEX: GMEXICOB)(Alfredo PÃ©rez)",
    "Oracle (NYS: ORCL)(Reggie Bradford)",
    "H.I.G. Capital(Christopher Laitala), Surgery Partners (NAS: SGRY)(Michael Doyle)",
    "CD3 Holdings, The Briggs Company",
    "Zimmer Biomet Holdings (NYS: ZBH)(David Dvorak)",
    "Berkshire Partners(Bradley Bloom), Carlyle AlpInvest, Crescent Capital Group, HarbourVest Partners(Ian Lane)",
    "AvalonBay Communities (NYS: AVB), Equity Residential (NYS: EQR)",
    "Sempra (NYS: SRE)",
    "Ames Watson, Blackstone (NYS: BX), Fanatics Holdings, Fidelity Management & Research Company, FMR (United States), Franklin Resources (NYS: BEN), Insight Partners (New York), Neuberger Berman, Silver Lake, SoftBank Investment Advisers",
    "American Realty Capital Healthcare Trust(Nicholas Schorsch)",
    "Carson Private Capital, Double Eagle Acquisition(Jeffrey Sagansky)",
    "Charlesbank Capital Partners(Jon Biotti), TRP Capital Partners",
    "Cannae Holdings (NYS: CNNE)(Brent Bickett)",
    "Blue Wolf Capital Partners(Jeremy Kogler), Constitution Capital Partners, HarbourVest Partners, Leavitt Equity Partners(Andrew Clark)",
    "ProMedica Health Systems, Quality Care Properties(Mark Ordan)",
    "Benchmark Electronics (NYS: BHE)",
    "Nexstar Media Group (NAS: NXST)(Perry Sook)",
    "American Industrial Partners, Shape Technologies Group",
    "Thomson Reuters (TSE: TRI)(Brian Peccarelli)",
    "MegaPath Holding",
    "Marlin Equity Partners(Nick Kaiser), Openwave Messaging",
    "CFT Capital Partners, Equity Group Investments, HPS Investment Partners, JVC Investment Partners",
    "Praxair(Eduardo Menezes)",
    "Metalmark Capital(Fazle Husain)",
    "MNX Global Logistics, St. Cloud Capital(Benjamin Hom)",
    "PulteGroup (NYS: PHM)(Richard Dugas)",
    "American Securities(Marc Saiontz)",
    "Cognizant Technology Solutions (NAS: CTSH)(Francisco D'Souza)",
    "Kohlberg Kravis Roberts (NYS: KKR)(Rony Ma)",
    "Apollo Asset Management (NYS: APO)(Laurence Berg)",
    "Eurofins Scientific (PAR: ERF)(Gilles Martin)",
    "Wipro (BOM: 507685)(Jeffrey Heenan-Jalil)",
    "TZP Group(Harris Newman)",
    "Buckingham Strategic Wealth(Adam Birenbaum)",
    "Audax Private Equity, Olympus Partners(David Cardenas)",
    "Sun Communities (NYS: SUI)",
    "inVentiv Health, Liberty Lane Partners, Talisman Capital Partners, Thomas H. Lee Partners(Todd Abbrecht)",
    "GreenSpace Brands(Matthew Teichman)",
    "Model N(Zack Rinat)",
    "Parthenon Capital Partners, SVB Financial Group",
    "Cohesive Capital Partners, Ergo Partners, One Rock Capital Partners(Tony Lee)",
    "Eir Partners, New Mountain Capital",
    "Promethean Investments",
    "Cathay Financial Holdings (TAI: 2882)(David Sun), Cathay Life Insurance",
    "Trane Technologies (NYS: TT)(David Regnery)",
    "Chemtrade Logistics (TSE: CHE.UN)(Mark Davis)",
    "Getronics(Nana Baffour), GSH Private Capital",
    "Korea National Oil, Samsung C&T (Acquired in 2015)",
    "Kinderhook Industries(Christian Michalik), ZP Better Together(Sherri Turpin)",
    "Parexel International(Josef Von Rickenbach)",
    "Omnicell (NAS: OMCL)",
    "Advent International(Steven Collins), Cohesive Capital Partners",
    "N. Harris Computer",
    "Kohlberg & Company(Ahmed Wahla)",
    "Constellation Software (TSE: CSU)",
    "CommScope Holding Company (NAS: COMM)(Marvin Edwards)",
    "Crestview Partners(Jeffrey Marcus), Cumulus Media (PINX: CMLS)(Lewis Dickey), Heller Equity Capital, Macquarie Asset Management, Ridgemont Equity Partners(Robert Sheridan), UBS Group (SWX: UBSG)",
    "Falcon Investments, The Gladstone Companies, Vistria Group(Philip Alphonse)",
    "Danaher (NYS: DHR)",
    "ADT (IT Security Company) (NYS: ADT), Apollo Asset Management (NYS: APO)(Marc Becker), Fisher Lynch Capital, Koch Equity Development",
    "Platinum Equity",
    "Court Square (Private Equity)(Michael Delaney)",
    "Amentum Services (NYS: AMTM)(John Vollmer), American Securities(Benjamin Dickson), Lindsay Goldberg(Russell Triedman), Peachtree Equity Partners",
    "Roark Capital Group(Neal Aronson)",
    "Pediatrix Medical Group (NYS: MD)(Roger Medel)",
    "Dell Technologies (NYS: DELL)(John Swainson)",
    "Carbonite",
    "Intercontinental Exchange (NYS: ICE)(Jeffrey Sprecher)",
    "Sony Music Entertainment",
    "Leonard Green & Partners, Varsity Brands(Joe Raines)",
    "Advent International(John Maldonado), Eshelman Ventures",
    "JVCKenwood (TKS: 6632)(Haruo Kawahara)",
    "Farallon Capital Management(Jason Fish), Golub Capital(Gregory Cashman), Mill Road Capital(Scott Scharfman), Rubio's Coastal Grill(Ralph Rubio)",
    "CapitalG, TPG (NAS: TPG)(David Trujillo)",
    "Glacier Restaurant Group(Brad Ridgeway)",
    "Kohlberg Kravis Roberts (NYS: KKR)(Nathaniel Taylor)",
    "Lincare Holdings(Kristen Hoefer)",
    "Aberdeen Asset Management, Ace Equity Partners(Denis Tse), Asia-IO Advisors(Denis Tse), Axiom Asia Private Capital, Redview Capital(Jin Yi), TR Capital",
    "Warner Bros. Entertainment",
    "The Children's Place (NAS: PLCE)",
    "TowerBrook Capital Partners(Jonathan Bilzin)",
    "GTT Communications(Richard Calder)",
    "Kohlberg Kravis Roberts (NYS: KKR)(Herald Chen), Temasek Holdings",
    "KPS Capital Partners(Michael Psaros)",
    "Jordan Health Services, Palladium Equity Partners, Trinity Hunt Partners(Peter Stein), W Capital Partners",
    "Cressey & Company(Paul Diaz), Leonard Green & Partners(John Baumer)",
    "Odyssey Investment Partners",
    "Gryphon Investors(Keith Stimson)",
    "Vroom (Internet Retail) (NAS: VRM)",
    "Del Monte (Singapore) (SES: D03)(Rolando Gapud)",
    "The J.M. Smucker Company (NYS: SJM)(Peter Farah)",
    "Great Point Partners(Jeffrey Jay)",
    "Keyw(William Weber)",
    "Soros Fund Management",
    "Enghouse Systems (TSE: ENGH)(Sunil Diaz)",
    "Holiday Inn Club Vacations(Don Harrill)",
    "Ar2, Corsair Capital(Jeremy Schein)",
    "Patterson Companies(Scott Anderson)",
    "Honeywell (NAS: HON)",
    "Masimo (NAS: MASI)(Joseph Kiani)",
    "Computer Sciences( IT Consulting and Outsourcing)(John Lawrie)",
    "Investcorp(Maud Brown), Mumtalakat (Private Equity)",
    "Werfen (Spain)(Carlos Pascual)",
    "Anthology (Florida)(James Milton), Leeds Equity Partners(Robert Bernstein), Veritas Capital(Ramzi Musallam)",
    "CapitalG(Gene Frantz), Hellman & Friedman(Anupam Mishra)",
    "Comvest Partners(Maneesh Chawla)",
    "Blackstone (NYS: BX)(Neil Simpkins), Change Healthcare(Neil de Crescenzo), Hellman & Friedman(Allen Thorpe)",
    "3M (NYS: MMM)(Michael Roman)",
    "Bain Capital(Nigel Walder), Ergo Partners",
    "Oracle (NYS: ORCL)",
    "Heartland Dental(Patrick Bauer), Kohlberg Kravis Roberts (NYS: KKR)(James Momtazee)",
    "Bain Capital, Twin Bridge Capital Partners",
    "Tutor.com(Amanda Ginsberg)",
    "GFL Environmental (NYS: GFL)(Patrick Dovigi)",
    "Centerbridge Partners(William Rahm)",
    "American Air Filter International(Philip Whitaker)",
    "Itron (NAS: ITRI)(Mark de Vere White)",
    "Maranon Capital, Stone Canyon Industries(James Fordyce)",
    "Chroma(Tom Bolger)",
    "Drum Capital Management, Paulson & Co.(John Paulson), TriArtisan Capital Advisors(Rohit Manocha)",
    "Ares Credit Group, Blackstone (NYS: BX), Blackstone Credit and Insurance, Brigade Capital Management, Fidelity, RBC Capital Markets",
    "The ONE Group Hospitality (NAS: STKS)(Emanuel Hilario)",
    "The Home Depot (NYS: HD)(Craig Menear)",
    "Golden Gate Capital(Rishi Chandna)",
    "HarbourVest Partners, Hellman & Friedman(Allen Thorpe)",
    "Mitra Adiperkasa (IDX: MAPI)",
    "Endo International",
    "Graycliff Partners, Mark Andy(Kevin Wilken)",
    "Gallatin Point Capital(Matthew Botein), Jacobs Asset Management",
    "TPG (NAS: TPG)(Jeffrey Rhodes)",
    "Alta Global Ventures, Blackstone (NYS: BX)(David Kestnbaum)",
    "BWC Terminals(Michael Suder), JP Morgan Asset Management",
    "Kraft Foods Group",
    "GE Holding SPA",
    "Cinven(Alex Leslie), VC23 Investors",
    "Cogir Senior Living Canada(Jeffrey Lozon), Welltower (NYS: WELL)(George Chapman)",
    "Audax Private Debt, MODE Global(James Damman), York Capital Management",
    "Hanwha Aerospace Company (KRX: 012450)",
    "Trimont Real Estate Advisors",
    "Dobbs Management Service, Stephens, TriArtisan Capital Advisors(Gerald Cromack)",
    "Raytheon",
    "Aon (NYS: AON)(Eric Andersen)",
    "MTY Food Group (TSE: MTY)(Stanley Ma)",
    "Dynatrace (NYS: DT)(John Van Siclen), Thoma Bravo(Orlando Bravo)",
    "Acadia Capital Group, Access Industries(Donald Wagner), Kohlberg Kravis Roberts (NYS: KKR)(John Park), Nobel Partners",
    "Dell-VMWare Tracking",
    "Global Payments (NYS: GPN)(Jeffrey Sloan)",
    "Element Materials Technology (London)(Joseph Wetz), Temasek Holdings",
    "HPS Investment Partners(Nobuyuki Idei), Tennenbaum Capital Partners(Howard Levkowitz)",
    "TTM Technologies (NAS: TTMI)(Thomas Edman)",
    "Pan Pacific International Holdings (TKS: 7532)(Naoki Yoshida)",
    "Calibre Group",
    "Brigade Capital Management, CVC Capital Partners (AMS: CVC)",
    "Cision US(Peter Granat), GTCR(Mark Anderson)",
    "Naked Brand Group(Justin Davis-Rice)",
    "Enghouse Systems (TSE: ENGH)(Stephen Sadler)",
    "Bain Capital Ventures(Benjamin Nye), BMC Software(Ayman Sayed), Kohlberg Kravis Roberts (NYS: KKR)(John Park)",
    "SDCL Efficiency Income Trust (LON: SEIT)(Jonathan Maxwell)",
    "ABC Technologies(Todd Sheppelman)",
    "Cornerstone OnDemand(Adam Miller)",
    "Barings, Frog Design, TA Associates Management(Michael Berk)",
    "Yageo (TAI: 2327)(Dora Chang)",
    "Ad Hoc Group, Apollo Asset Management (NYS: APO)(Christopher Lahoud)",
    "Ontic Engineering & Manufacturing(Gareth Hall)",
    "Promus Equity Partners(Steven Brown), TriArtisan Capital Advisors",
    "Salesforce (NYS: CRM)(Parker Harris)",
    "Blackstone (NYS: BX)(Katharine Keenan)",
    "Candle-lite(Calvin Johnston), Centre Lane Partners(Mayank Singh)",
    "Ingenic (SHE: 300223)",
    "Haymaker Acquisition Corp. I",
    "Hein Park Capital Management",
    "Anbang Insurance Group Company(Philip Yee)",
    "Summit Hosting",
    "Crane NXT (NYS: CXT)(Aaron Saak)",
    "Clearlake Capital Group(Paul Huber), Flexpoint Ford",
    "OmniVision Integrated (SHG: 603501)",
    "Authentic Brands Group(Jamie Salter), BlackRock Private Equity Partners(Colm Lanigan), CVC Capital Partners (AMS: CVC)(Christopher Stadler), General Atlantic(Andrew Crawford), GIC Private, HPS Investment Partners(Scot French), Jasper Ridge Partners, Leonard Green & Partners(Jonathan Seiffer), Lion Capital(Lyndon Lea)",
    "Elliott Investment Management, Speyside Equity(Eric Wiklendt)",
    "AEA Investors(Andreas Kramvis)",
    "Cencosud (SGO: CENCOSUD)(Matias Videla)",
    "Platinum Equity(Louis Samson)",
    "Aspen Surgical(Jason Krieser), Linden (Chicago)",
    "CVC Capital Partners (AMS: CVC)(Christopher Baldwin)",
    "ACE & Company (Geneva), Cinven(Michael Korzinstone)",
    "Adobe (Multimedia and Design Software) (NAS: ADBE)(Bradley Rencher)",
    "Hilton Grand Vacations (HGV)(Mark Wang)",
    "Graham Partners(Robert Newbold)",
    "Poly (Electronics )(Joseph Burton)",
    "StorCentric(Mihir Shah)",
    "Signet Jewelers (NYS: SIG)(Virginia Drosos)",
    "Fairfax Financial Holdings (TSE: FFH)",
    "Vector Capital (California)(David Fishman)",
    "Warburg Pincus(Stephanie Geveda)",
    "KSL Capital Partners(Eric Resnick)",
    "Tata Consulting Engineers(Amit Sharma)",
    "Ullico(Edward Smith)",
    "TransUnion (NYS: TRU)(Christopher Cartwright)",
    "Kohlberg Kravis Roberts (NYS: KKR)(Andre Jakubowski)",
    "Safariland(Warren Kanders)",
    "L Catterton(Marc Magliacano)",
    "Equicorp Partners, Inspire Brands(Paul Brown), Roark Capital Group(Neal Aronson)",
    "Investment Management Corporation of Ontario, Kohlberg Kravis Roberts (NYS: KKR)(John Park), Ten Eleven Ventures(Alexander Doll)",
    "Energy Capital Partners(Andrew Singer), Pantheon Infrastructure (LON: PINC)",
    "Bain Capital(Adam Nebesar)",
    "Wise Road Capital",
    "Hybridge Capital Management, Stellex Capital Management(Michael Stewart), Tail End Capital Partners(Justin Bertram)",
    "N. Harris Computer(Jerry Canada)",
    "Shentel (NAS: SHEN)(Christopher French)",
    "Ardian, Kohlberg Kravis Roberts (NYS: KKR), Stemar Capital",
    "Clearhaven Partners(Christopher Ryan)",
    "Clearlake Capital Group(James Pade)",
    "Apollo Asset Management (NYS: APO)(Joanna Rose)",
    "Avolin(Tim Rentowl), ESW Capital",
    "Thales (Aerospace and Defence) (PAR: HO)(Patrice Caine)",
    "Ares Management (NYS: ARES), Bain Capital(David Humphrey), Bain Capital Tech Opportunities, Ergo Partners, GIC Private, Hellman & Friedman(Allen Thorpe)",
    "Olympus Partners(David Cardenas)",
    "El Super(Carlos Matas)",
    "ArcLight Capital Partners(Daniel Revers)",
    "First Sentier Investors(John Ma), Patriot Rail Company(John Fenton)",
    "From You Flowers(Michael Chapin), Tenth Avenue Holdings",
    "Clayton, Dubilier & Rice(Harsh Agarwal)",
    "TD Synnex (NYS: SNX)(Dennis Polk)",
    "Bausch + Lomb (TSE: BLCO)",
    "IXL Learning(Paul Mishkin)",
    "Ares Management (NYS: ARES), Benefit Street Partners, BlackRock (NYS: BLK), Blue Owl Capital (NYS: OWL)(Erik Bissonnette), Goldman Sachs Asset Management, Golub Capital",
    "American Industrial Partners(Randall Swift), Sachs Capital, The Brock Group(W.C. Gary)",
    "Carpenter Company",
    "PhenixFIN (NAS: PFX)(David Lorber)",
    "xAI"
]


if __name__ == "__main__":
    # In practice, you would pass your full 'Investors_exit' list here
    generate_manual_mapping_template(acquirer_data)